### ISSUE TITLE
How did GoLang rewrite work for you?

### ISSUE THREAD

**Issue by tomByrer** [egoist/aho#3]
How long did your rewrite take.  How much faster is it now?

Just curious if I should learn Go ;)

**Comment by egoist** [comment]
This project is pretty simple so it only took an hour, it doesn't do any intensive work so the speed doesn't matter now, the Node version is also fast cause it doesn't use any dependencies, but when the project gets bigger, the difference will show.

Overall Go is a nice replacement for building CLIs, GoReleaser makes it trivial to distribute Go binaries on GitHub releases or Homebrew, that's one reason I didn't go for Rust. Another reason is the Go compiler is so fast, it makes writing code a joy 🥶

**Comment by tomByrer** [comment]
> that's one reason I didn't go for Rust

You read my mind for my next question. ;)
Good point about GoReleaser; was thinking of making small utilities in [Vlang}(https://vlang.io/).

Thank you for responce!
